site_url: https://proleagueitalia.it

backend:
  name: git-gateway
  branch: main
  base_url: https://proleagueitalia.it
  identity:
    roles:
      - admin
      - editor

login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "lega-inglese"
    label: "Lega Inglese"
    folder: "content/leghe/lega-inglese"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", media_folder: "images/squadre/inglese", public_folder: "/images/squadre/inglese" }
  - name: "lega-italiana"
    label: "Lega Italiana"
    folder: "content/leghe/lega-italiana"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", media_folder: "images/squadre/italiana", public_folder: "/images/squadre/italiana" }
  - name: "lega-francese"
    label: "Lega Francese"
    folder: "content/leghe/lega-francese"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", media_folder: "images/squadre/francese", public_folder: "/images/squadre/francese" }
  - name: "lega-tedesca"
    label: "Lega Tedesca"
    folder: "content/leghe/lega-tedesca"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", media_folder: "images/squadre/tedesca", public_folder: "/images/squadre/tedesca" }
  - name: "lega-spagnola"
    label: "Lega Spagnola"
    folder: "content/leghe/lega-spagnola"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", media_folder: "images/squadre/spagnola", public_folder: "/images/squadre/spagnola" }
