site_url: https://proleagueitalia.it

backend:
  name: git-gateway
  branch: main
  base_url: https://proleagueitalia.it
  identity:
    roles:
      - admin
      - editor

login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "lega-inglese"
    label: "Lega Inglese"
    folder: "content/leghe/lega-inglese"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Partite giocate", name: "pg", widget: "number" }
      - { label: "Vittorie", name: "v", widget: "number" }
      - { label: "Pareggi", name: "p", widget: "number" }
      - { label: "Sconfitte", name: "s", widget: "number" }
      - { label: "Gol fatti", name: "gf", widget: "number" }
      - { label: "Gol subiti", name: "gs", widget: "number" }
      - { label: "Differenza reti", name: "dr", widget: "number" }

  - name: "lega-italiana"
    label: "Lega Italiana"
    folder: "content/leghe/lega-italiana"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Partite giocate", name: "pg", widget: "number" }
      - { label: "Vittorie", name: "v", widget: "number" }
      - { label: "Pareggi", name: "p", widget: "number" }
      - { label: "Sconfitte", name: "s", widget: "number" }
      - { label: "Gol fatti", name: "gf", widget: "number" }
      - { label: "Gol subiti", name: "gs", widget: "number" }
      - { label: "Differenza reti", name: "dr", widget: "number" }

  - name: "lega-francese"
    label: "Lega Francese"
    folder: "content/leghe/lega-francese"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Partite giocate", name: "pg", widget: "number" }
      - { label: "Vittorie", name: "v", widget: "number" }
      - { label: "Pareggi", name: "p", widget: "number" }
      - { label: "Sconfitte", name: "s", widget: "number" }
      - { label: "Gol fatti", name: "gf", widget: "number" }
      - { label: "Gol subiti", name: "gs", widget: "number" }
      - { label: "Differenza reti", name: "dr", widget: "number" }

  - name: "lega-spagnola"
    label: "Lega Spagnola"
    folder: "content/leghe/lega-spagnola"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Partite giocate", name: "pg", widget: "number" }
      - { label: "Vittorie", name: "v", widget: "number" }
      - { label: "Pareggi", name: "p", widget: "number" }
      - { label: "Sconfitte", name: "s", widget: "number" }
      - { label: "Gol fatti", name: "gf", widget: "number" }
      - { label: "Gol subiti", name: "gs", widget: "number" }
      - { label: "Differenza reti", name: "dr", widget: "number" }

  - name: "lega-tedesca"
    label: "Lega Tedesca"
    folder: "content/leghe/lega-tedesca"
    create: true
    fields:
      - { label: "Squadra", name: "squadra", widget: "string" }
      - { label: "Partite giocate", name: "pg", widget: "number" }
      - { label: "Vittorie", name: "v", widget: "number" }
      - { label: "Pareggi", name: "p", widget: "number" }
      - { label: "Sconfitte", name: "s", widget: "number" }
      - { label: "Gol fatti", name: "gf", widget: "number" }
      - { label: "Gol subiti", name: "gs", widget: "number" }
      - { label: "Differenza reti", name: "dr", widget: "number" }
