site_url: https://proleagueitalia.it

backend:
  name: git-gateway
  branch: main
  base_url: https://proleagueitalia.it
  identity:
    roles:
      - admin
      - editor


login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "squadre"
    label: "Squadre"
    folder: "content/squadre"
    create: true
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Allenatore", name: "allenatore", widget: "string" }

